server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 9001

database:
  driverClass: org.postgresql.Driver
  user: root
  url: jdbc:postgresql://localhost:5432/testdb
